<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-31 at 15:01:47.
 */
require_once '/var/www/ascus/classes/validation/AlphaValidator.php';

class AlphaValidatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AlphaValidator
     */
    protected $alphaValidator;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->alphaValidator = new AlphaValidator("First Name");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AlphaValidator::validate
     */
    public function testValidate() {
        $this->assertEquals(true, $this->alphaValidator->validate("asbA",""));
        $this->assertEquals(false, $this->alphaValidator->validate(" ",""));
        $this->assertEquals(false, $this->alphaValidator->validate("A1a",""));
        $this->assertEquals(false, $this->alphaValidator->validate("a 1",""));
    }

}
