<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-01 at 19:23:42.
 */
require_once '/var/www/ascus/classes/validation/MinimumLengthValidator.php';

class MinimumLengthValidatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var MinimumLengthValidator
     */
    protected $minimumLengthValidator;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers MinimumLengthValidator::validate
     */
    public function testValidate() {
        $this->minimumLengthValidator = new MinimumLengthValidator(1);
        $this->assertEquals(true,$this->minimumLengthValidator->validate("test",""));
        $this->assertEquals(false,$this->minimumLengthValidator->validate("",""));
        
        $this->minimumLengthValidator = new MinimumLengthValidator(4);
        $this->assertEquals(true,$this->minimumLengthValidator->validate("test",""));
        $this->assertEquals(false,$this->minimumLengthValidator->validate("the",""));
    }

}
