<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-30 at 15:52:22.
 */

require_once '/var/www/ascus/classes/validation/NumericValidator.php';

class NumericValidatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var NumericValidator
     */
    protected $numericValidator;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
 
        $this->numericValidator = new NumericValidator("Phone Number");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers NumericValidator::validate
     * @todo   Implement testValidate().
     */
    public function testValidate() {
        $this->assertEquals(true, $this->numericValidator->validate("1",""));
        $this->assertEquals(true, $this->numericValidator->validate("0101",""));
        $this->assertEquals(true, $this->numericValidator->validate("44101",""));
        $this->assertEquals(true, $this->numericValidator->validate("0000000",""));

        $this->assertEquals(false, $this->numericValidator->validate("1AB",""));
        $this->assertEquals(false, $this->numericValidator->validate(" ",""));
        $this->assertEquals(false, $this->numericValidator->validate("0121!1",""));
    }

}
