<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-31 at 14:53:56.
 */
require_once '/var/www/ascus/classes/validation/RequiredValidator.php';
class RequiredValidatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var RequiredValidator
     */
    protected $requiredValidator;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->requiredValidator = new RequiredValidator();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RequiredValidator::validate
     */
    public function testValidate() {
       $this->assertEquals(FALSE,$this->requiredValidator->validate("",""));
       $this->assertEquals(TRUE,$this->requiredValidator->validate(" ",""));
    }

}
