<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-30 at 15:52:33.
 */
require_once '/var/www/ascus/php/validation/MixedCaseValidator.php';

class MixedCaseValidatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var MixedCaseValidator
     */
    protected $mixedCaseValidator;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->mixedCaseValidator = new MixedCaseValidator("First Name");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers MixedCaseValidator::validate
     */
    public function testValidate() {
        $this->assertEquals(true, $this->mixedCaseValidator->validate("ABC"));
        $this->assertEquals(true, $this->mixedCaseValidator->validate("1A"));
        $this->assertEquals(true, $this->mixedCaseValidator->validate("ab1 B"));

        $this->assertEquals(false, $this->mixedCaseValidator->validate("1"));
        $this->assertEquals(false, $this->mixedCaseValidator->validate("a1"));
        $this->assertEquals(false, $this->mixedCaseValidator->validate(""));
    }

}
