<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-31 at 14:53:56.
 */
require_once '/var/www/ascus/php/validation/NonEmptyValidator.php';
class NonEmptyValidator extends PHPUnit_Framework_TestCase {

    /**
     * @var NonEmptyValidator
     */
    protected $nonEmptyValidator;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->nonEmptyValidator = new NonEmptyValidator("First Name");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers NonBlankValidator::validate
     */
    public function testValidate() {
       $this->assertEquals(true,$this->nonEmptyValidator->validate(" "));
       $this->assertEquals(false,$this->nonEmptyValidator->validate(""));
       
    }

}
