<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-22 at 21:27:29.
 */
require_once '/var/www/ascus/php/Database.php';

class DatabaseTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Database
     */
    protected $database;

    /**
     * @covers Database::__consrtuct
     * 
     */
    public function test__consrtuct() {
        $this->database = new Database("read");
        $this->database = new Database("write");
    }

    /**
     * @covers Database::__consrtuct
     * @expectedException InvalidArgumentException
     * @expectedExceptionMessage Invalid User Type
     */
    public function test__consrtuctWithException() {
        $this->database = new Database("admin");
        $this->database = new Database("");
    }

    /**
     * @covers Database::connect
     */
    public function testconnect() {
        $this->database = new Database("read");
        $this->database->connect();
        
         $this->database = new Database("write");
        $this->database->connect();
    }

}
